package semantic

func GetIDTerm() map[string]int {
	IDTable := []string{"Variable", "Constant", "useless", "log", "sin", "cos", "tg", "ctg", "lg", "ln", "^", "+", "-", "*", "/", "=", "?", "(", ")", ",", ";", "#"}
	IDTerm := make(map[string]int)
	for i, item := range IDTable {
		IDTerm[item] = i
	}
	return IDTerm
}

func GetIDNonTerm() map[string]int {
	IDTable := []string{"S'", "S", "A", "B", "C", "D"}
	IDNonTerm := make(map[string]int)
	for i, item := range IDTable {
		IDNonTerm[item] = i
	}
	return IDNonTerm
}

func GetString(ID int, IDTerm map[string]int) string {
	str := ""
	for item, i := range IDTerm {
		if ID == i {
			str = item
		}
	}
	return str
}

type Pair struct {
	Left  string
	Right int
}

func GetGramTableAndSLRTableAndGoToTable() ([]Pair, [][]Pair, [][]Pair) {
	GramTable := make([]Pair, 22)
	GramTable[2] = Pair{Left: "S", Right: 4}
	GramTable[3] = Pair{Left: "S", Right: 3}
	GramTable[4] = Pair{Left: "A", Right: 3}
	GramTable[5] = Pair{Left: "A", Right: 3}
	GramTable[6] = Pair{Left: "A", Right: 1}
	GramTable[7] = Pair{Left: "B", Right: 3}
	GramTable[8] = Pair{Left: "B", Right: 3}
	GramTable[9] = Pair{Left: "B", Right: 1}
	GramTable[10] = Pair{Left: "C", Right: 6}
	GramTable[11] = Pair{Left: "C", Right: 4}
	GramTable[12] = Pair{Left: "C", Right: 3}
	GramTable[13] = Pair{Left: "C", Right: 4}
	GramTable[14] = Pair{Left: "C", Right: 1}
	GramTable[15] = Pair{Left: "D", Right: 2}
	GramTable[16] = Pair{Left: "D", Right: 2}
	GramTable[17] = Pair{Left: "D", Right: 2}
	GramTable[18] = Pair{Left: "D", Right: 2}
	GramTable[19] = Pair{Left: "D", Right: 1}
	GramTable[20] = Pair{Left: "D", Right: 1}
	GramTable[21] = Pair{Left: "D", Right: 3}

	SLRTable := make([][]Pair, 44)
	GoToTable := make([][]Pair, 44)
	for i := range SLRTable {
		SLRTable[i] = make([]Pair, 22)
		GoToTable[i] = make([]Pair, 6)
	}
	SLRTable[0][0] = Pair{Left: "s", Right: 2}
	SLRTable[0][16] = Pair{Left: "s", Right: 3}
	SLRTable[1][21] = Pair{Left: "s", Right: 44}
	SLRTable[2][15] = Pair{Left: "s", Right: 4}
	SLRTable[3][0] = Pair{Left: "s", Right: 13}
	SLRTable[3][1] = Pair{Left: "s", Right: 14}
	SLRTable[3][4] = Pair{Left: "s", Right: 10}
	SLRTable[3][5] = Pair{Left: "s", Right: 10}
	SLRTable[3][6] = Pair{Left: "s", Right: 10}
	SLRTable[3][7] = Pair{Left: "s", Right: 10}
	SLRTable[3][8] = Pair{Left: "s", Right: 10}
	SLRTable[3][9] = Pair{Left: "s", Right: 10}
	SLRTable[3][11] = Pair{Left: "s", Right: 11}
	SLRTable[3][12] = Pair{Left: "s", Right: 12}
	SLRTable[3][17] = Pair{Left: "s", Right: 15}
	SLRTable[3][3] = Pair{Left: "s", Right: 8}
	SLRTable[4][0] = Pair{Left: "s", Right: 13}
	SLRTable[4][1] = Pair{Left: "s", Right: 14}
	SLRTable[4][4] = Pair{Left: "s", Right: 10}
	SLRTable[4][5] = Pair{Left: "s", Right: 10}
	SLRTable[4][6] = Pair{Left: "s", Right: 10}
	SLRTable[4][7] = Pair{Left: "s", Right: 10}
	SLRTable[4][8] = Pair{Left: "s", Right: 10}
	SLRTable[4][9] = Pair{Left: "s", Right: 10}
	SLRTable[4][11] = Pair{Left: "s", Right: 11}
	SLRTable[4][12] = Pair{Left: "s", Right: 12}
	SLRTable[4][17] = Pair{Left: "s", Right: 15}
	SLRTable[4][3] = Pair{Left: "s", Right: 8}
	SLRTable[5][11] = Pair{Left: "s", Right: 17}
	SLRTable[5][12] = Pair{Left: "s", Right: 18}
	SLRTable[5][20] = Pair{Left: "s", Right: 43}
	SLRTable[6][11] = Pair{Left: "r", Right: 6}
	SLRTable[6][12] = Pair{Left: "r", Right: 6}
	SLRTable[6][13] = Pair{Left: "s", Right: 19}
	SLRTable[6][14] = Pair{Left: "s", Right: 20}
	SLRTable[6][18] = Pair{Left: "r", Right: 6}
	SLRTable[6][20] = Pair{Left: "r", Right: 6}
	SLRTable[7][11] = Pair{Left: "r", Right: 9}
	SLRTable[7][12] = Pair{Left: "r", Right: 9}
	SLRTable[7][13] = Pair{Left: "r", Right: 9}
	SLRTable[7][14] = Pair{Left: "r", Right: 9}
	SLRTable[7][18] = Pair{Left: "r", Right: 9}
	SLRTable[7][20] = Pair{Left: "r", Right: 9}
	SLRTable[8][17] = Pair{Left: "s", Right: 21}
	SLRTable[9][11] = Pair{Left: "r", Right: 14}
	SLRTable[9][12] = Pair{Left: "r", Right: 14}
	SLRTable[9][13] = Pair{Left: "r", Right: 14}
	SLRTable[9][14] = Pair{Left: "r", Right: 14}
	SLRTable[9][10] = Pair{Left: "s", Right: 22}
	SLRTable[9][18] = Pair{Left: "r", Right: 14}
	SLRTable[9][20] = Pair{Left: "r", Right: 14}
	SLRTable[10][17] = Pair{Left: "s", Right: 23}
	SLRTable[11][0] = Pair{Left: "s", Right: 24}
	SLRTable[11][1] = Pair{Left: "s", Right: 25}
	SLRTable[12][0] = Pair{Left: "s", Right: 26}
	SLRTable[12][1] = Pair{Left: "s", Right: 27}
	SLRTable[13][10] = Pair{Left: "r", Right: 19}
	SLRTable[13][11] = Pair{Left: "r", Right: 19}
	SLRTable[13][12] = Pair{Left: "r", Right: 19}
	SLRTable[13][13] = Pair{Left: "r", Right: 19}
	SLRTable[13][14] = Pair{Left: "r", Right: 19}
	SLRTable[13][18] = Pair{Left: "r", Right: 19}
	SLRTable[13][20] = Pair{Left: "r", Right: 19}
	SLRTable[14][10] = Pair{Left: "r", Right: 20}
	SLRTable[14][11] = Pair{Left: "r", Right: 20}
	SLRTable[14][12] = Pair{Left: "r", Right: 20}
	SLRTable[14][13] = Pair{Left: "r", Right: 20}
	SLRTable[14][14] = Pair{Left: "r", Right: 20}
	SLRTable[14][18] = Pair{Left: "r", Right: 20}
	SLRTable[14][20] = Pair{Left: "r", Right: 20}
	SLRTable[15][0] = Pair{Left: "s", Right: 13}
	SLRTable[15][1] = Pair{Left: "s", Right: 14}
	SLRTable[15][4] = Pair{Left: "s", Right: 10}
	SLRTable[15][5] = Pair{Left: "s", Right: 10}
	SLRTable[15][6] = Pair{Left: "s", Right: 10}
	SLRTable[15][7] = Pair{Left: "s", Right: 10}
	SLRTable[15][8] = Pair{Left: "s", Right: 10}
	SLRTable[15][9] = Pair{Left: "s", Right: 10}
	SLRTable[15][11] = Pair{Left: "s", Right: 11}
	SLRTable[15][12] = Pair{Left: "s", Right: 12}
	SLRTable[15][17] = Pair{Left: "s", Right: 15}
	SLRTable[15][3] = Pair{Left: "s", Right: 8}
	SLRTable[16][11] = Pair{Left: "s", Right: 17}
	SLRTable[16][12] = Pair{Left: "s", Right: 18}
	SLRTable[16][20] = Pair{Left: "s", Right: 29}
	SLRTable[17][0] = Pair{Left: "s", Right: 13}
	SLRTable[17][1] = Pair{Left: "s", Right: 14}
	SLRTable[17][4] = Pair{Left: "s", Right: 10}
	SLRTable[17][5] = Pair{Left: "s", Right: 10}
	SLRTable[17][6] = Pair{Left: "s", Right: 10}
	SLRTable[17][7] = Pair{Left: "s", Right: 10}
	SLRTable[17][8] = Pair{Left: "s", Right: 10}
	SLRTable[17][9] = Pair{Left: "s", Right: 10}
	SLRTable[17][11] = Pair{Left: "s", Right: 11}
	SLRTable[17][12] = Pair{Left: "s", Right: 12}
	SLRTable[17][17] = Pair{Left: "s", Right: 15}
	SLRTable[17][3] = Pair{Left: "s", Right: 8}
	SLRTable[18][0] = Pair{Left: "s", Right: 13}
	SLRTable[18][1] = Pair{Left: "s", Right: 14}
	SLRTable[18][4] = Pair{Left: "s", Right: 10}
	SLRTable[18][5] = Pair{Left: "s", Right: 10}
	SLRTable[18][6] = Pair{Left: "s", Right: 10}
	SLRTable[18][7] = Pair{Left: "s", Right: 10}
	SLRTable[18][8] = Pair{Left: "s", Right: 10}
	SLRTable[18][9] = Pair{Left: "s", Right: 10}
	SLRTable[18][11] = Pair{Left: "s", Right: 11}
	SLRTable[18][12] = Pair{Left: "s", Right: 12}
	SLRTable[18][17] = Pair{Left: "s", Right: 15}
	SLRTable[18][3] = Pair{Left: "s", Right: 8}
	SLRTable[19][0] = Pair{Left: "s", Right: 13}
	SLRTable[19][1] = Pair{Left: "s", Right: 14}
	SLRTable[19][4] = Pair{Left: "s", Right: 10}
	SLRTable[19][5] = Pair{Left: "s", Right: 10}
	SLRTable[19][6] = Pair{Left: "s", Right: 10}
	SLRTable[19][7] = Pair{Left: "s", Right: 10}
	SLRTable[19][8] = Pair{Left: "s", Right: 10}
	SLRTable[19][9] = Pair{Left: "s", Right: 10}
	SLRTable[19][11] = Pair{Left: "s", Right: 11}
	SLRTable[19][12] = Pair{Left: "s", Right: 12}
	SLRTable[19][17] = Pair{Left: "s", Right: 15}
	SLRTable[19][3] = Pair{Left: "s", Right: 8}
	SLRTable[20][0] = Pair{Left: "s", Right: 13}
	SLRTable[20][1] = Pair{Left: "s", Right: 14}
	SLRTable[20][4] = Pair{Left: "s", Right: 10}
	SLRTable[20][5] = Pair{Left: "s", Right: 10}
	SLRTable[20][6] = Pair{Left: "s", Right: 10}
	SLRTable[20][7] = Pair{Left: "s", Right: 10}
	SLRTable[20][8] = Pair{Left: "s", Right: 10}
	SLRTable[20][9] = Pair{Left: "s", Right: 10}
	SLRTable[20][11] = Pair{Left: "s", Right: 11}
	SLRTable[20][12] = Pair{Left: "s", Right: 12}
	SLRTable[20][17] = Pair{Left: "s", Right: 15}
	SLRTable[20][3] = Pair{Left: "s", Right: 8}
	SLRTable[21][0] = Pair{Left: "s", Right: 13}
	SLRTable[21][1] = Pair{Left: "s", Right: 14}
	SLRTable[21][11] = Pair{Left: "s", Right: 11}
	SLRTable[21][12] = Pair{Left: "s", Right: 12}
	SLRTable[21][17] = Pair{Left: "s", Right: 15}
	SLRTable[22][0] = Pair{Left: "s", Right: 13}
	SLRTable[22][1] = Pair{Left: "s", Right: 14}
	SLRTable[22][11] = Pair{Left: "s", Right: 11}
	SLRTable[22][12] = Pair{Left: "s", Right: 12}
	SLRTable[22][17] = Pair{Left: "s", Right: 15}
	SLRTable[23][0] = Pair{Left: "s", Right: 13}
	SLRTable[23][1] = Pair{Left: "s", Right: 14}
	SLRTable[23][11] = Pair{Left: "s", Right: 11}
	SLRTable[23][12] = Pair{Left: "s", Right: 12}
	SLRTable[23][17] = Pair{Left: "s", Right: 15}
	SLRTable[24][10] = Pair{Left: "r", Right: 15}
	SLRTable[24][11] = Pair{Left: "r", Right: 15}
	SLRTable[24][12] = Pair{Left: "r", Right: 15}
	SLRTable[24][13] = Pair{Left: "r", Right: 15}
	SLRTable[24][14] = Pair{Left: "r", Right: 15}
	SLRTable[24][18] = Pair{Left: "r", Right: 15}
	SLRTable[24][20] = Pair{Left: "r", Right: 15}
	SLRTable[25][10] = Pair{Left: "r", Right: 17}
	SLRTable[25][11] = Pair{Left: "r", Right: 17}
	SLRTable[25][12] = Pair{Left: "r", Right: 17}
	SLRTable[25][13] = Pair{Left: "r", Right: 17}
	SLRTable[25][14] = Pair{Left: "r", Right: 17}
	SLRTable[25][18] = Pair{Left: "r", Right: 17}
	SLRTable[25][20] = Pair{Left: "r", Right: 17}
	SLRTable[26][10] = Pair{Left: "r", Right: 16}
	SLRTable[26][11] = Pair{Left: "r", Right: 16}
	SLRTable[26][12] = Pair{Left: "r", Right: 16}
	SLRTable[26][13] = Pair{Left: "r", Right: 16}
	SLRTable[26][14] = Pair{Left: "r", Right: 16}
	SLRTable[26][18] = Pair{Left: "r", Right: 16}
	SLRTable[26][20] = Pair{Left: "r", Right: 16}
	SLRTable[27][10] = Pair{Left: "r", Right: 18}
	SLRTable[27][11] = Pair{Left: "r", Right: 18}
	SLRTable[27][12] = Pair{Left: "r", Right: 18}
	SLRTable[27][13] = Pair{Left: "r", Right: 18}
	SLRTable[27][14] = Pair{Left: "r", Right: 18}
	SLRTable[27][18] = Pair{Left: "r", Right: 18}
	SLRTable[27][20] = Pair{Left: "r", Right: 18}
	SLRTable[28][11] = Pair{Left: "s", Right: 17}
	SLRTable[28][12] = Pair{Left: "s", Right: 18}
	SLRTable[28][18] = Pair{Left: "s", Right: 37}
	SLRTable[29][21] = Pair{Left: "r", Right: 2}
	SLRTable[30][11] = Pair{Left: "r", Right: 4}
	SLRTable[30][12] = Pair{Left: "r", Right: 4}
	SLRTable[30][13] = Pair{Left: "s", Right: 19}
	SLRTable[30][14] = Pair{Left: "s", Right: 20}
	SLRTable[30][18] = Pair{Left: "r", Right: 4}
	SLRTable[30][20] = Pair{Left: "r", Right: 4}
	SLRTable[31][11] = Pair{Left: "r", Right: 5}
	SLRTable[31][12] = Pair{Left: "r", Right: 5}
	SLRTable[31][13] = Pair{Left: "s", Right: 19}
	SLRTable[31][14] = Pair{Left: "s", Right: 20}
	SLRTable[31][18] = Pair{Left: "r", Right: 5}
	SLRTable[31][20] = Pair{Left: "r", Right: 5}
	SLRTable[32][11] = Pair{Left: "r", Right: 7}
	SLRTable[32][12] = Pair{Left: "r", Right: 7}
	SLRTable[32][13] = Pair{Left: "r", Right: 7}
	SLRTable[32][14] = Pair{Left: "r", Right: 7}
	SLRTable[32][18] = Pair{Left: "r", Right: 7}
	SLRTable[32][20] = Pair{Left: "r", Right: 7}
	SLRTable[33][11] = Pair{Left: "r", Right: 8}
	SLRTable[33][12] = Pair{Left: "r", Right: 8}
	SLRTable[33][13] = Pair{Left: "r", Right: 8}
	SLRTable[33][14] = Pair{Left: "r", Right: 8}
	SLRTable[33][18] = Pair{Left: "r", Right: 8}
	SLRTable[33][20] = Pair{Left: "r", Right: 8}
	SLRTable[34][18] = Pair{Left: "s", Right: 39}
	SLRTable[34][19] = Pair{Left: "s", Right: 38}
	SLRTable[35][11] = Pair{Left: "r", Right: 12}
	SLRTable[35][12] = Pair{Left: "r", Right: 12}
	SLRTable[35][13] = Pair{Left: "r", Right: 12}
	SLRTable[35][14] = Pair{Left: "r", Right: 12}
	SLRTable[35][18] = Pair{Left: "r", Right: 12}
	SLRTable[35][20] = Pair{Left: "r", Right: 12}
	SLRTable[36][18] = Pair{Left: "s", Right: 40}
	SLRTable[37][10] = Pair{Left: "r", Right: 21}
	SLRTable[37][11] = Pair{Left: "r", Right: 21}
	SLRTable[37][12] = Pair{Left: "r", Right: 21}
	SLRTable[37][13] = Pair{Left: "r", Right: 21}
	SLRTable[37][14] = Pair{Left: "r", Right: 21}
	SLRTable[37][18] = Pair{Left: "r", Right: 21}
	SLRTable[37][20] = Pair{Left: "r", Right: 21}
	SLRTable[38][0] = Pair{Left: "s", Right: 13}
	SLRTable[38][1] = Pair{Left: "s", Right: 14}
	SLRTable[38][11] = Pair{Left: "s", Right: 11}
	SLRTable[38][12] = Pair{Left: "s", Right: 12}
	SLRTable[38][17] = Pair{Left: "s", Right: 15}
	SLRTable[39][11] = Pair{Left: "r", Right: 11}
	SLRTable[39][12] = Pair{Left: "r", Right: 11}
	SLRTable[39][13] = Pair{Left: "r", Right: 11}
	SLRTable[39][14] = Pair{Left: "r", Right: 11}
	SLRTable[39][18] = Pair{Left: "r", Right: 11}
	SLRTable[39][20] = Pair{Left: "r", Right: 11}
	SLRTable[40][11] = Pair{Left: "r", Right: 13}
	SLRTable[40][12] = Pair{Left: "r", Right: 13}
	SLRTable[40][13] = Pair{Left: "r", Right: 13}
	SLRTable[40][14] = Pair{Left: "r", Right: 13}
	SLRTable[40][18] = Pair{Left: "r", Right: 13}
	SLRTable[40][20] = Pair{Left: "r", Right: 13}
	SLRTable[41][18] = Pair{Left: "s", Right: 42}
	SLRTable[42][11] = Pair{Left: "r", Right: 10}
	SLRTable[42][12] = Pair{Left: "r", Right: 10}
	SLRTable[42][13] = Pair{Left: "r", Right: 10}
	SLRTable[42][14] = Pair{Left: "r", Right: 10}
	SLRTable[42][18] = Pair{Left: "r", Right: 10}
	SLRTable[42][20] = Pair{Left: "r", Right: 10}
	SLRTable[43][21] = Pair{Left: "r", Right: 3}

	GoToTable[0][1] = Pair{Left: "s", Right: 1}
	GoToTable[3][2] = Pair{Left: "s", Right: 5}
	GoToTable[3][3] = Pair{Left: "s", Right: 6}
	GoToTable[3][4] = Pair{Left: "s", Right: 7}
	GoToTable[3][5] = Pair{Left: "s", Right: 9}
	GoToTable[4][2] = Pair{Left: "s", Right: 16}
	GoToTable[4][3] = Pair{Left: "s", Right: 6}
	GoToTable[4][4] = Pair{Left: "s", Right: 7}
	GoToTable[4][5] = Pair{Left: "s", Right: 9}
	GoToTable[15][2] = Pair{Left: "s", Right: 28}
	GoToTable[15][3] = Pair{Left: "s", Right: 6}
	GoToTable[15][4] = Pair{Left: "s", Right: 7}
	GoToTable[15][5] = Pair{Left: "s", Right: 9}
	GoToTable[17][3] = Pair{Left: "s", Right: 30}
	GoToTable[17][4] = Pair{Left: "s", Right: 7}
	GoToTable[17][5] = Pair{Left: "s", Right: 9}
	GoToTable[18][3] = Pair{Left: "s", Right: 31}
	GoToTable[18][4] = Pair{Left: "s", Right: 7}
	GoToTable[18][5] = Pair{Left: "s", Right: 9}
	GoToTable[19][4] = Pair{Left: "s", Right: 32}
	GoToTable[19][5] = Pair{Left: "s", Right: 9}
	GoToTable[20][4] = Pair{Left: "s", Right: 33}
	GoToTable[20][5] = Pair{Left: "s", Right: 9}
	GoToTable[21][5] = Pair{Left: "s", Right: 34}
	GoToTable[22][5] = Pair{Left: "s", Right: 35}
	GoToTable[23][5] = Pair{Left: "s", Right: 36}
	GoToTable[38][5] = Pair{Left: "s", Right: 41}

	return GramTable, SLRTable, GoToTable
}
